### ISSUE TITLE
Remove references to expired AMIs

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-cs-infra#76]
per https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-2527

We need to update or remove existing instances/launch templates that are referencing expired AMIs:
Instance:

account_name |	instance_id	| instance_name
-- | -- | --
Unity-Test |	i-083ad8a365d7de732	| ucstestcluster-defaultgroup-Node
Unity-Test |	i-088d2a1449f6bf5a5	| UCS-dev-cluster-UCS-dev-clusterNodeGroup-Node
Unity-Test |	i-0f6c6879efe08f7b5	| apigatewaytestingredux-defaultgroupNodeGroup-Node

Launch templates should be removed, especially if no longer being used

Env | Launch Template | Name
-- | -- | --
Unity-Dev | lt-0f2deffb5caa64bce | eksctl-apigatewaytestingredux5-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-0395cc867fc4d74e5 | eksctl-ucsnightlycluster-nodegroup-group1NodeGroup
Unity-Dev | lt-08c42c10d6c01e3c0 | eks-0ac496aa-404d-5951-cda6-0adc086209fc
Unity-Dev | lt-01de94b975f870dca | eksctl-ryandeploytestcluster-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-0d2060cc8a163e518 | eksctl-unity-test-do-i-work-2-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-07a978ccf2ac99178 | eksctl-uas-dev-sdap-nodegroup-sdap-driverNodeGroup
Unity-Dev | lt-0839cffb96ee520f4 | eksctl-ryan-eks-dev-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-044a0e9d180d9d06a | eks-8cc496aa-4110-29d8-89ba-5e413950816c
Unity-Dev | lt-0bf591f5315cad7ca | eksctl-unity-test-do-i-work-3-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-0a86cbd58ce0bad74 | eksctl-ryan-eks-test-nodegroup-group1NodeGroup
Unity-Dev | lt-035b66bb96e7132fb | eksctl-testclusteract7-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-0be97bfac448cee6d | eksctl-uas-dev-sdap-nodegroup-sdap-workerNodeGroup
Unity-Dev | lt-097e90e03fc08761a | eksctl-apigw-test-cluster2-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-0c5b7fb6e08a53cfe | eksctl-testclusteract6-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-022697b1ba34bd002 | eksctl-testng4-nodegroup-group1NodeGroup
Unity-Dev | lt-061228ba11331f926 | eksctl-testng4-nodegroup-group2NodeGroup
Unity-Dev | lt-0ca937fd2f261db51 | eksctl-apigw-test-cluster-nodegroup-defaultgroupNodeGroup
  |   |  
Unity-Sips-Test | lt-044c74b794be82cd3 | UnityNodeGroup-20231002155905405300000002
Unity-Sips-Test | lt-057030c61431a9809 | UnityNodeGroup-20231003080043633800000002
Unity-Sips-Test | lt-0eee7d719a99f0f11 | UnityNodeGroup-20230928161323750300000002
Unity-Sips-Test | lt-0657572f47249cf6b | UnityNodeGroup-20231002103407738900000002
Unity-Sips-Test | lt-0e39a5370fba1ac99 | UnityNodeGroup-20230928154854837000000002
Unity-Sips-Test | lt-000f2530b9372d940 | UnityNodeGroup-20231013185121687200000001
Unity-Sips-Test | lt-0ce713e6a2243743e | UnityNodeGroup-20231003092037879100000002
Unity-Sips-Test | lt-0b18b287f9f2c008f | UnityNodeGroup-20231013201036803600000003
Unity-Sips-Test | lt-049d3e598f8d24dd3 | UnityNodeGroup-20231018160957727800000003
Unity-Sips-Test | lt-0dd46a4c7aa943fea | UnityNodeGroup-20231002085712387200000002
Unity-Sips-Test | lt-0be652d30b0adbb62 | UnityNodeGroup-20231002112316859500000002
Unity-Sips-Test | lt-0c863deb0677d5cf0 | UnityNodeGroup-20231002124420881300000003
Unity-Sips-Test | lt-07d6abf4aea0ed89d | UnityNodeGroup-20230929132632298600000002
Unity-Sips-Test | lt-00e3efc530bc4c372 | UnityNodeGroup-20230929104325735900000002
Unity-Sips-Test | lt-06b05b729d8f58580 | UnityNodeGroup-20231003094625883000000002
Unity-Sips-Test | lt-0198a49b3a50b1e7e | UnityNodeGroup-20231002093702264300000002
  |   |  
Unity-Test | lt-03c1315c2991d5867 | eks-76c1138a-d7fa-b8bb-9c9e-5f24d39c5c56
Unity-Test | lt-04f57479aae2bd4c8 | eksctl-ucstestcluster-nodegroup-defaultgroup
Unity-Test | lt-0a3d0b3f96d749b8e | eks-6cc2e38a-e6d4-2ce3-82d9-71ef48622c75
Unity-Test | lt-098c192731c4c82a7 | eksctl-testestest-nodegroup-testestestNodeGroup
Unity-Test | lt-0e446cc70afeae4ea | eksctl-UCS-dev-cluster-nodegroup-UCS-dev-clusterNodeGroup
Unity-Test | lt-0a5224742e5cd2744 | eks-d2c38755-52a4-497f-ae8c-8dd520a16384
Unity-Test | lt-0ceed9e907c0b3732 | eksctl-apigatewaytestingredux-nodegroup-defaultgroupNodeGroup

**Comment by galenatjpl** [comment]
@LucaCinquini , it looks like a large number of these originated from SPS services/resources.  Related to this ticket:  https://github.com/unity-sds/unity-cs/issues/378, do you think you can leverage either the MCP SSM params, or the CS params to make sure the correct AMI is used?

**Comment by LucaCinquini** [comment]
In his latest PR, @drewm-jpl is using updated AMIs - but are the values retrieved from SSM parameters?

**Comment by galenatjpl** [comment]
@LucaCinquini @drewm-jpl see my latest comment in https://github.com/unity-sds/unity-cs/issues/378

**Comment by mike-gangl** [comment]
This has been resolved/closed on the MCP side. Thanks for the effort everyone!
